spring.application.name=helpdesk

spring.datasource.url=jdbc:postgresql://localhost:5434/helpdeskdb
spring.datasource.username=admin
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=validate